[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc_version = "0.8.30"
via-ir = true
optimizer = true
optimizer_runs = 4294967295

[profile.ci]
ffi = false

[lint]
exclude_lints = ["unsafe-cheatcode"]
