[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc_version = "0.8.30"
via-ir = true
optimizer = true
optimizer_runs = 4294967295
ignored_error_codes = [3628]

[lint]
exclude_lints = ["unsafe-cheatcode"]

[fmt]
tab_width = 2
